## ADMIN operations

### Create flight
POST http://localhost:8080/admin/flights
Content-Type:  application/json

{
  "flightNumber": "FR123",
  "departureAirport": "DUB",
  "departureTime": "2026-10-10T14:30:00+01:00[Europe/Dublin]",
  "arrivalAirport": "LON",
  "arrivalTime": "2026-10-10T15:45:00+01:00[Europe/London]",
  "totalSeats": 180
}

### Create another flight
POST http://localhost:8080/admin/flights
Content-Type: application/json

{
  "flightNumber": "YU123",
  "departureAirport": "BEG",
  "departureTime": "2025-10-10T14:30:00+01:00[Europe/Belgrade]",
  "arrivalAirport": "JFK",
  "arrivalTime": "2025-10-11T15:45:00+01:00[America/New_York]",
  "totalSeats": 3
}

### Delete flight
DELETE http://localhost:8080/admin/flights/1

## USER operations

### Search all flights
GET http://localhost:8080/flights

### Search by route
GET http://localhost:8080/flights?departureAirport=DUB&arrivalAirport=LON

### Search by date
GET http://localhost:8080/flights?date=2026-10-10

### Search by route
GET http://localhost:8080/flights?date=2026-10-10&departureAirport=DUB&arrivalAirport=LON

### Get available seats for a flight
GET http://localhost:8080/flights/1/seats

### Create a booking
POST http://localhost:8080/flights/1/bookings
Content-Type: application/json

{
  "passengerName": "Danilo Gasljevic",
  "seatNumber": 10
}

### Cancel booking
DELETE http://localhost:8080/bookings/1

### Confirm booking
POST http://localhost:8080/bookings/1/confirm